env:
  commonjs: true
  es6: true
  node: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    experimentalObjectRestSpread: true
rules: {}
